<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="LFCS_joint" type="fixed">
        <parent link="LFF_link" />
        <child link="LFCS_link" />
        <origin xyz="0 0 ${-2*foot_radius}" rpy="0 0 0" />
    </joint>

</robot>