<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="RFT_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="RFH_link" />
        <origin xyz="${trunk_actuators_length/2.0} ${-(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${T_lower_limit/180.0*pi}" 
               upper="${T_upper_limit/180.0*pi}" 
               effort="${T_effort}" 
               velocity="${T_velocity}" />
        <axis xyz="-1 0 0" />
    </joint>

</robot>