<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="single_joint_urdf">

<xacro:property name="stator_length" value="0.5"/>
<xacro:property name="rotor_radius" value="0.2"/>
<xacro:property name="rotor_size" value="0.1"/>
<xacro:property name="rotor_length" value="0.5"/>


<xacro:macro name="single_joint_macro" params="name parent_name x y inertia pos_max pos_min vel_max effort_max">
    
    <link name="${name}_stator">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="10.0"/> 
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/> 
        </inertial>

        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${stator_length} ${stator_length} ${stator_length}"/>
            </geometry>
            <material name="">
                <color rgba="1.0 0.0 0.0 1.0"/>
            </material>
        </visual>
    </link>

    <gazebo reference="${name}_stator">
        <material>Gazebo/Red</material>
    </gazebo>


    <link name="${name}_rotor">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="1.0"/> 
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="${inertia}"/> 
        </inertial>

        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${rotor_radius}" length="${rotor_size}"/>
            </geometry>
           <material name="">
                <color rgba="0.0 1.0 0.0 1.0"/>
            </material>
        </visual>
        <visual>
            <origin xyz="${-rotor_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${rotor_length} ${rotor_size} ${rotor_size}"/>
            </geometry>
            <material name="">
                <color rgba="0.0 0.0 1.0 1.0"/>
            </material>
        </visual>
    </link>

    <gazebo reference="${name}_rotor">
        <material>Gazebo/Green</material>
    </gazebo>

    <joint name="${parent_name}_${name}" type="fixed">
        <origin xyz="${x} ${y} ${stator_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="${parent_name}"/>
        <child link="${name}_stator"/>
    </joint>

    <joint name="${name}_joint" type="revolute">
        <origin xyz="${stator_length/2 + rotor_size/2} 0.0 0.0" rpy="0.0 ${PI/2} 0.0"/>
        <parent link="${name}_stator"/>
        <child link="${name}_rotor"/>
        <axis xyz="0.0 0.0 1.0"/>
        <limit lower="${pos_min}" upper="${pos_max}" effort="${effort_max}" velocity="${vel_max}"/>
    </joint>
</xacro:macro>
</robot>