<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name = "meldog_hip">



    <xacro:property name="hip_length" value="0.2"/>
    <xacro:property name="hip_width" value="0.15"/>
    <xacro:property name="hip_height" value="0.075"/>

    <xacro:property name="hip_mass" value="3.0"/>

    <xacro:macro name="hip_link" params="position">
        <link name="hip_${position}_link">
            <inertial>
                <origin xyz="${hip_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${hip_mass}"/>
                 <mass value="${trunk_mass}"/> 
            <inertia ixx="${1/12*trunk_mass*(hip_width*hip_width + hip_height*hip_height)}" ixy="0.0" ixz="0.0" iyy="${1/12*trunk_mass*(hip_length*hip_length + hip_height*hip_height)}" iyz=".0" izz="${1/12*trunk_mass*(hip_length*hip_length + hip_width*hip_width)}"/> 
            </inertial>

            <visual name="hip_${position}_link_visual">
                <origin xyz="${hip_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${hip_length} ${hip_width} ${hip_height}"/>
                </geometry>
                <material name="">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>

            <collision name="hip_${position}_link_collision">
                <origin xyz="${hip_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <box size="${hip_length} ${hip_width} ${hip_height}"/>
                </geometry>
            </collision>
            
        </link>
    </xacro:macro>
</robot>