<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name = "meldog_shank">

    <xacro:property name="shank_length" value="0.5"/>
    <xacro:property name="shank_radius" value="0.05"/>

    <xacro:property name="shank_mass" value = "1.0"/>

    <xacro:macro name="shank_link" params="position">
        <link name="shank_${position}_link">
            <inertial>
                <origin xyz="0.0 0.0 ${-shank_length/2}" rpy="0.0 0.0 0.0"/>
                <mass value="${shank_mass}"/>
                <inertia ixx="${1/12*shank_mass*(3*shank_radius*shank_radius+shank_length*shank_length)}" ixy="0.0" ixz="0.0" iyy="${1/12*shank_mass*(3*shank_radius*shank_radius+shank_length*shank_length)}" iyz="0.0" izz="${1/2*shank_mass*shank_radius*shank_radius}"/>
            </inertial>

            <visual name="shank_${position}_link_visual">
                <origin xyz="0.0 0.0 ${-shank_length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${shank_radius}" length="${shank_length}"/>
                </geometry>
                <material name="">
                    <color rgba="1.0 1.0 0.0 1.0"/>
                </material>
            </visual>

            <collision name="shank_${position}_link_collision">
                <origin xyz="0.0 0.0 ${-shank_length/2}" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${shank_radius}" length="${shank_length}"/>
                </geometry>
            </collision>
           
        </link>
    </xacro:macro>
</robot>