<?xml version="1.0"?>
<robot name="meldog_core" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="base_properties.urdf.xacro" />
    <xacro:include filename="macros/macros.urdf.xacro" />
    <xacro:include filename="links/trunk.urdf.xacro" />

    <!-- LINKS -->

        <!-- Left front leg links -->

            <!-- Left front hip link -->
            <xacro:include filename="links/hip/LFH_link.urdf.xacro"/>

            <!-- Left front upper limb link -->
            <xacro:include filename="links/upper_limb/LFUL_link.urdf.xacro"/>

            <!-- Left front lower limb link -->
            <xacro:include filename="links/lower_limb/LFLL_link.urdf.xacro"/>

            <!-- Left front foot link -->
            <xacro:include filename="links/foot/LFF_link.urdf.xacro"/>

        <!-- Right front leg links -->

            <!-- Right front hip link -->
            <xacro:include filename="links/hip/RFH_link.urdf.xacro"/>

            <!-- Right front upper limb link -->
            <xacro:include filename="links/upper_limb/RFUL_link.urdf.xacro"/>

            <!-- Right front lower limb link -->
            <xacro:include filename="links/lower_limb/RFLL_link.urdf.xacro"/>

            <!-- Right front foot link -->
            <xacro:include filename="links/foot/RFF_link.urdf.xacro"/>

        <!-- Left rear leg links -->

            <!-- Left rear hip link -->
            <xacro:include filename="links/hip/LRH_link.urdf.xacro"/>

            <!-- Left rear upper limb link -->
            <xacro:include filename="links/upper_limb/LRUL_link.urdf.xacro"/>

            <!-- Left rear lower limb link -->
            <xacro:include filename="links/lower_limb/LRLL_link.urdf.xacro"/>

            <!-- Left rear foot link -->
            <xacro:include filename="links/foot/LRF_link.urdf.xacro"/>


        <!-- Right rear leg links -->

            <!-- Right rear hip link -->
            <xacro:include filename="links/hip/RRH_link.urdf.xacro"/>

            <!-- Right rear upper limb link -->
            <xacro:include filename="links/upper_limb/RRUL_link.urdf.xacro"/>

            <!-- Right rear lower limb link -->
            <xacro:include filename="links/lower_limb/RRLL_link.urdf.xacro"/>

            <!-- Right rear foot link -->
            <xacro:include filename="links/foot/RRF_link.urdf.xacro"/>

    
    <!-- JOINTS -->

        <!-- Left front leg joints -->

            <!-- Left front trunk joint -->
            <xacro:include filename="joints/trunk/LFT_joint.urdf.xacro"/>

            <!-- Left front hip joint -->
            <xacro:include filename="joints/hip/LFH_joint.urdf.xacro"/>

            <!-- Left front knee joint -->
            <xacro:include filename="joints/knee/LFK_joint.urdf.xacro"/>

            <!-- Left front foot joint -->
            <xacro:include filename="joints/foot/LFF_joint.urdf.xacro"/>

        <!-- Right front leg joints -->

            <!-- Right front trunk joint -->
            <xacro:include filename="joints/trunk/RFT_joint.urdf.xacro"/>

            <!-- Right front hip joint -->
            <xacro:include filename="joints/hip/RFH_joint.urdf.xacro"/>

            <!-- Right front knee joint -->
            <xacro:include filename="joints/knee/RFK_joint.urdf.xacro"/>

            <!-- Right front foot joint -->
            <xacro:include filename="joints/foot/RFF_joint.urdf.xacro"/>

        <!-- Left rear leg joints -->

            <!-- Left rear trunk joint -->
            <xacro:include filename="joints/trunk/LRT_joint.urdf.xacro"/>

            <!-- Left rear hip joint -->
            <xacro:include filename="joints/hip/LRH_joint.urdf.xacro"/>

            <!-- Left rear knee joint -->
            <xacro:include filename="joints/knee/LRK_joint.urdf.xacro"/>

            <!-- Left rear foot joint -->
            <xacro:include filename="joints/foot/LRF_joint.urdf.xacro"/>

        <!-- Right rear leg joints -->

            <!-- Right rear trunk joint -->
            <xacro:include filename="joints/trunk/RRT_joint.urdf.xacro"/>

            <!-- Right rear hip joint -->
            <xacro:include filename="joints/hip/RRH_joint.urdf.xacro"/>

            <!-- Right rear knee joint -->
            <xacro:include filename="joints/knee/RRK_joint.urdf.xacro"/>

            <!-- Right rear foot joint -->
            <xacro:include filename="joints/foot/RRF_joint.urdf.xacro"/>

    <!-- Right rear leg joints -->
    <!-- <joint name="RRT_joint" type="revolute">
        <parent link="trunk_link" />
        <child link="RRH_link" />
        <origin xyz="${-trunk_actuators_length/2.0} ${-(trunk_base_width+trunk_actuators_width)/2.0} 0" rpy="0 0 0" />
        <limit lower="${trunk_hip_lower_limit/180.0*pi}" 
               upper="${trunk_hip_upper_limit/180.0*pi}" 
               effort="${trunk_hip_effort}" 
               velocity="${trunk_hip_velocity}" />
        <axis xyz="-1 0 0" />
    </joint> -->

    <!-- <joint name="RRH_joint" type="revolute">
        <parent link="RRH_link" /> 
        <child link="RRUL_link" />
        <origin xyz="${-hip_upper_limb_x}
                     ${-hip_upper_limb_y}
                     ${hip_upper_limb_z}" 
                rpy="0 0 0" />
        <limit lower="${hip_upper_limb_lower_limit/180.0*pi}" 
               upper="${hip_upper_limb_upper_limit/180.0*pi}" 
               effort="${hip_upper_limb_effort}" 
               velocity="${hip_upper_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint> -->

    <!-- <joint name="RRK_joint" type="revolute">
        <parent link="RRUL_link" />
        <child link="RRLL_link" />
        <origin xyz="0 0 ${-upper_limb_length}" rpy="0 0 0" />
        <limit lower="${upper_limb_lower_limb_lower_limit/180.0*pi}" 
               upper="${upper_limb_lower_limb_upper_limit/180.0*pi}" 
               effort="${upper_limb_lower_limb_effort}" 
               velocity="${upper_limb_lower_limb_velocity}" />
        <axis xyz="0 1 0" />
    </joint> -->

    <!-- <joint name="RRF_joint" type="fixed">
        <parent link="RRLL_link" />
        <child link="RRF_link" />
        <origin xyz="0 0 ${-lower_limb_length_to_foot}" rpy="0 0 0" />
    </joint> -->

</robot>