controller_manager:
  ros__parameters:
    update_rate: 500

    joint_controller:
      type: joint_controller/JointController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_controller:
  ros__parameters:
    joint_names:
      - LRT_joint
      - LRH_joint
      - LRK_joint

    joint_params:

      LRT_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LRH_joint: 
        position_max: 3.14
        position_min: -3.14
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

      LRK_joint: 
        position_max: 2.793
        position_min: -2.793
        position_offset: 0.0
        velocity_max: 18.906
        effort_max: 34.895

    frequency: 500.0

    pid_gains:

      LRT_joint:
        p: 100.0
        d: 1.00
        i: 0.0
        ilimit: 0.0
      LRH_joint:
        p: 100.0
        d: 1.00
        i: 0.0
        ilimit: 0.0
      LRK_joint:
        p: 100.0
        d: 1.00
        i: 0.0
        ilimit: 0.0
