controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - LRT_joint
      - LRH_joint
      - LRK_joint

    command_joints:
      - LRT_joint
      - LRH_joint
      - LRK_joint


    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 1000.0
    state_publish_rate: 1000.0
    allow_nonzero_velocity_at_trajectory_end: false

    gains:
      LRT_joint:
        d: 1.5
        ff_velocity_scale: 0.0
        i: 15.0
        i_clamp: 30.0
        p: 70.0
      LRH_joint:
        d: 1.5
        ff_velocity_scale: 0.0
        i: 15.0
        i_clamp: 30.0
        p: 70.0
      LRK_joint:
        d: 1.5
        ff_velocity_scale: 0.0
        i: 15.0
        i_clamp: 30.0
        p: 70.0