name: Build ROS 2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - uses: ros-tooling/setup-ros@0.6.1
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_leg_tests
          target-ros2-distro: humble
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_interfaces_tests
          target-ros2-distro: humble
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_description
          target-ros2-distro: humble
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_simple_description
          target-ros2-distro: humble
          skip-tests: true
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: meldog_launch_tests
          target-ros2-distro: humble
          skip-tests: true 
