name: Lint ROS 2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_py:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # We exclude cppcheck due to https://github.com/ament/ament_lint/pull/345
        linter: [pep8]
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@0.6.1
      - uses: ros-tooling/action-ros-lint@0.1.3
        with:
          linter: ${{ matrix.linter }}
          package-name: ${{matrix.package}}
          matrix:
            package: [meldog_logger, meldog_bridge]
